name: Docker Image CI

on:
  push:
    branches: [ "nodejs16" ]
  pull_request:
    branches: [ "nodejs16" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag s2i-angular-httpd24:$(date +%s)
